listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

http_api {
    enabled         on;
    listen          1985;
}

srt_server {
    enabled on;
    listen 10080;
}

vhost __defaultVhost__ {
    http_hooks {
        enabled         on;
        on_publish      http://host.docker.internal:5092/srs/on-publish;
        on_unpublish    http://host.docker.internal:5092/srs/on-unpublish;
    }

    forward {
        enabled         on;
        backend         http://host.docker.internal:5092/srs/forward;
    }
}
